import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/design-system/src/components/atoms/Sonner";
import { ThemeProvider } from "@/components/provider/ThemeProvider";
import { SidebarProvider } from "@/design-system/src/components/organisms/SideBar";
import { cookies } from "next/headers";

import { inter } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  // Sidebar is open if cookie value is "true", closed otherwise
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} font-sans antialiased min-h-screen flex`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider defaultOpen={defaultOpen}>
            <Toaster />
            <div className="flex flex-1 w-full">{children}</div>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
