import type { Metadata } from "next";
import { Toaster } from "@/design-system/src/components/atoms/Sonner";
import AppSidebar from "@/components/AppSidebar";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/provider/ThemeProvider";
import { SidebarProvider } from "@/design-system/src/components/organisms/SideBar";
import { cookies } from "next/headers";

import { inter } from "@/lib/fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

  return (
    <html lang="en" suppressHydrationWarning>
      {/* ✅ MUST apply `inter.variable` (or `inter.className`) here */}
      <body
        className={`${inter.variable} font-sans antialiased min-h-screen flex`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider defaultOpen={defaultOpen}>
            <Toaster />
            <AppSidebar />
            <main className="w-full flex flex-col">
              <Navbar />
              <div className="px-4 flex-1">{children}</div>
            </main>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
