import { defineConfig } from 'tsup'

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm', 'cjs'],
  dts: true,
  sourcemap: true,
  clean: true,
  external: [
    'react',
    'react-dom',
    'framer-motion',
    'class-variance-authority',
    'clsx',
    'tailwind-merge',
    'tailwindcss-animate',
    '@radix-ui/*',
    'lucide-react',
    'react-day-picker',
    'date-fns',
    'zod',
    'react-hook-form',
    'sonner',
    'next-themes',
    'next/font',
    'next/image',
    'next/link',
    'next/router',
    'next/head',
    'next/dynamic',
    'next/script',
    'next/navigation',
    'next/headers',
    'next/cache',
    'next/font',
    'next/font/google',
    'next/font/local',
    'react-syntax-highlighter',
    'react-syntax-highlighter/dist/esm/styles/prism',
    'react-syntax-highlighter/dist/cjs/styles/prism',
    'react-syntax-highlighter/dist/esm/languages/prism/tsx',
    'react-syntax-highlighter/dist/cjs/languages/prism/tsx',
    'react-syntax-highlighter/dist/esm/languages/prism/typescript',
    'react-syntax-highlighter/dist/cjs/languages/prism/typescript',
    'react-syntax-highlighter/dist/esm/languages/prism/jsx',
    'react-syntax-highlighter/dist/cjs/languages/prism/jsx',
    'react-syntax-highlighter/dist/esm/languages/prism/javascript',
    'react-syntax-highlighter/dist/cjs/languages/prism/javascript',
    'react-syntax-highlighter/dist/esm/languages/prism/json',
    'react-syntax-highlighter/dist/cjs/languages/prism/json',
    'react-syntax-highlighter/dist/esm/languages/prism/bash',
    'react-syntax-highlighter/dist/cjs/languages/prism/bash',
    'react-syntax-highlighter/dist/esm/languages/prism/shell-session',
    'react-syntax-highlighter/dist/cjs/languages/prism/shell-session',
    'react-syntax-highlighter/dist/esm/languages/prism/diff',
    'react-syntax-highlighter/dist/cjs/languages/prism/diff',
    'react-syntax-highlighter/dist/esm/languages/prism/markdown',
    'react-syntax-highlighter/dist/cjs/languages/prism/markdown',
    'react-syntax-highlighter/dist/esm/languages/prism/markup',
    'react-syntax-highlighter/dist/cjs/languages/prism/markup',
    'react-syntax-highlighter/dist/esm/languages/prism/tsx',
    'react-syntax-highlighter/dist/cjs/languages/prism/tsx',
    'react-syntax-highlighter/dist/esm/languages/prism/typescript',
    'react-syntax-highlighter/dist/cjs/languages/prism/typescript',
    'react-syntax-highlighter/dist/esm/languages/prism/jsx',
    'react-syntax-highlighter/dist/cjs/languages/prism/jsx',
    'react-syntax-highlighter/dist/esm/languages/prism/javascript',
    'react-syntax-highlighter/dist/cjs/languages/prism/javascript',
    'react-syntax-highlighter/dist/esm/languages/prism/json',
    'react-syntax-highlighter/dist/cjs/languages/prism/json',
    'react-syntax-highlighter/dist/esm/languages/prism/bash',
    'react-syntax-highlighter/dist/cjs/languages/prism/bash',
    'react-syntax-highlighter/dist/esm/languages/prism/shell-session',
    'react-syntax-highlighter/dist/cjs/languages/prism/shell-session',
    'react-syntax-highlighter/dist/esm/languages/prism/diff',
    'react-syntax-highlighter/dist/cjs/languages/prism/diff',
    'react-syntax-highlighter/dist/esm/languages/prism/markdown',
    'react-syntax-highlighter/dist/cjs/languages/prism/markdown',
    'react-syntax-highlighter/dist/esm/languages/prism/markup',
    'react-syntax-highlighter/dist/cjs/languages/prism/markup',
  ],
  tsconfig: './tsconfig.json',
  outExtension({ format }) {
    return {
      js: format === 'esm' ? '.mjs' : '.cjs',
    }
  },
})
